name: Configure GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Automatically configure GitHub Pages to use the `/ap` path
          # This will create the necessary configuration in the repository
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The following will configure GitHub Pages to serve from the /ap path
          # This is equivalent to manually setting the custom path in repository settings
          path: '/'
